"""empty message

Revision ID: 5d7490cca12d
Revises: 6d1aed4a8690
Create Date: 2025-02-21 19:19:58.357164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d7490cca12d'
down_revision = '6d1aed4a8690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
