"""empty message

Revision ID: 753829170db7
Revises: 8bbfacef6af2
Create Date: 2025-02-19 13:47:43.395395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753829170db7'
down_revision = '8bbfacef6af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ultimo_login')

    # ### end Alembic commands ###
