"""empty message

Revision ID: 7daa33c8d6be
Revises: ee692fb74a1c
Create Date: 2025-02-20 11:36:16.434866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7daa33c8d6be'
down_revision = 'ee692fb74a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('historial_cambios_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('historial_cambios_ibfk_2', 'users', ['usuario_id'], ['id'])
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
