"""empty message

Revision ID: 8cad86db3e5c
Revises: 44713cf99199
Create Date: 2025-03-04 15:41:32.621524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cad86db3e5c'
down_revision = '44713cf99199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
