"""empty message

Revision ID: c4cb3e547ed2
Revises: 7737ff348d08
Create Date: 2025-02-19 13:07:14.114896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cb3e547ed2'
down_revision = '7737ff348d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datos_previos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.drop_column('datos_previos')

    # ### end Alembic commands ###
