"""empty message

Revision ID: ffc82788e1df
Revises: 5da7abbaeb2a
Create Date: 2025-02-13 12:15:54.663132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffc82788e1df'
down_revision = '5da7abbaeb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
